# Generated by Django 3.1.1 on 2020-09-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200922_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilepost',
            options={'ordering': ['-publication_date']},
        ),
    ]
