# Generated by Django 3.0.5 on 2020-08-02 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200803_0112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GreenLeafUser',
        ),
    ]
