# Generated by Django 3.0.5 on 2020-08-03 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0003_delete_greenleafuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenLeafUserProfile',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=63)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
