# Generated by Django 3.0.5 on 2020-08-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_greenleafuserprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenleafuserprofile',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='greenleafuserprofile',
            name='profile_picture',
            field=models.ImageField(default='/pictures/default.png', upload_to='pictures'),
        ),
        migrations.CreateModel(
            name='PostProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField(max_length=5000)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.GreenLeafUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.GreenLeafUserProfile')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.PostProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=1000)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.GreenLeafUserProfile')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.PostProfile')),
            ],
        ),
    ]
