# Generated by Django 3.1.1 on 2020-09-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Outwear', 'Верхняя одежда'), ('Underwear', 'Нижняя одежда'), ('Shoe', 'Обувь'), ('Accessory', 'Аксессуары')], default='Shoe', max_length=32),
            preserve_default=False,
        ),
    ]
